<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuar</name>
   <tag></tag>
   <elementGuidId>1f5220be-b195-427f-bfa6-e6018361c66e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.next-button.btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb9c4d41-4ea1-4f72-b5ce-1479d8588d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>accec54b-2a18-4cbb-873f-5185785dbf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Por favor seleccionar una opción para continuar</value>
      <webElementGuid>741315fe-c0aa-4519-8d1f-e31a4a173e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary next-button btn-block</value>
      <webElementGuid>fce7ac45-a25e-41b8-b2e3-f1e8656ae93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>94153abb-f719-40a8-b0ea-0af30ed718d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/block-ui[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row page-container IE-footer-container&quot;]/div[@class=&quot;col-12 p-0 content-wrap&quot;]/app-quote[1]/div[@class=&quot;d-flex flex-column&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/app-using[1]/div[@class=&quot;col-sm-12 offset-sm-0 col-md-10 offset-md-1 col-lg-8 offset-lg-2 space-mobile&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;using-content&quot;]/div[@class=&quot;container ml-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-12 col-xl-4 order-5 order-md-6 order-lg-6 order-xl-6 mt-5 p-0 d-flex align-items-center justify-content-center&quot;]/button[@class=&quot;btn btn-primary next-button btn-block&quot;]</value>
      <webElementGuid>ac8233d2-1fb5-43d9-89d8-04b7f23eaeee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>286435e7-d731-4f51-be7d-a6ab37c68faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/following::button[1]</value>
      <webElementGuid>757b6f0c-d912-4dbb-9d74-5026f13d95a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Taxi, Uber, Didi, Cabify u otras apps con fines comerciales)'])[1]/following::button[2]</value>
      <webElementGuid>dbd918d6-8909-46e7-939c-da24b6b00bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Tienes alguna duda?'])[1]/preceding::button[1]</value>
      <webElementGuid>2ddd1dd2-9f72-478d-9fd6-0b7d37059a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar']/parent::*</value>
      <webElementGuid>ec4e2d29-e496-45b3-ad59-f3b6b814ff23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>c912791f-0486-4426-8921-385e71532d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Por favor seleccionar una opción para continuar' and (text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>ce7dbb3f-1950-4c7b-a972-5e4c650a1698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
