<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2019</name>
   <tag></tag>
   <elementGuidId>cf2c7c2d-d2dc-4380-8a20-ee84715d1000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@value='2019']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92092659-53b5-47e1-be16-a7ab6ee3351b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5e43374b-7cde-46c3-b562-98fe081dc548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2019</value>
      <webElementGuid>395ab138-fd66-40b5-87a5-15adbdd21602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 2019 </value>
      <webElementGuid>c318e988-1527-4f31-be46-bd90292e2763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/block-ui[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row page-container IE-footer-container&quot;]/div[@class=&quot;col-12 p-0 content-wrap&quot;]/app-quote[1]/div[@class=&quot;d-flex flex-column&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/app-year[1]/div[@class=&quot;col-sm-12 offset-sm-0 col-md-10 offset-md-1 col-lg-8 offset-lg-2&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-12 dy_year_container_year&quot;]/div[1]/chubb-select[1]/div[@class=&quot;d-flex align-items-center justify-content-start margin-top-sm-3&quot;]/div[@class=&quot;chubb-select-container row d-flex align-items-center justify-content-start dy_year_years&quot;]/div[@class=&quot;option-container d-flex justify-content-center&quot;]/div[@class=&quot;option&quot;]</value>
      <webElementGuid>c43b1f4b-b1f1-4a99-9036-4197d6cc58ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@value='2019']</value>
      <webElementGuid>c5765c91-7f75-47bd-859d-058f07538a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿de qué año es tu auto?'])[1]/following::div[18]</value>
      <webElementGuid>9519d929-a0cb-455f-a783-1ca4e4762e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTRO'])[1]/preceding::div[11]</value>
      <webElementGuid>76a90a34-8b10-4b1c-a62c-c842442f4dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/preceding::div[13]</value>
      <webElementGuid>89b8855d-d4dd-4aa3-9f3f-5b7e8474f9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2019']/parent::*</value>
      <webElementGuid>766c6604-b4de-455e-9dc2-3299629c9ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>69e1f284-952a-47c4-9a7e-01954758470a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 2019 ' or . = ' 2019 ')]</value>
      <webElementGuid>4bc81741-fe20-47b5-b074-0cc8bd5f94a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
