<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FORD</name>
   <tag></tag>
   <elementGuidId>8448b6f4-8d2b-433d-aff3-4e21322c640d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@value='12-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>460e1a80-ac1c-453d-a651-6c31c8d8bce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>81a81bb2-7944-44e8-9929-1f77517cee4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12-18</value>
      <webElementGuid>dc6475de-87fe-4c68-b167-93b6cb30a5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FORD </value>
      <webElementGuid>45abb870-5824-48c1-9bc7-167dcb832b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/block-ui[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row page-container IE-footer-container&quot;]/div[@class=&quot;col-12 p-0 content-wrap&quot;]/app-quote[1]/div[@class=&quot;d-flex flex-column&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/app-brand[1]/div[@class=&quot;col-sm-12 offset-sm-0 col-md-10 offset-md-1 col-lg-8 offset-lg-2&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-12 col-lg-8 col-xl-8 col-xxl-7&quot;]/chubb-select[1]/div[@class=&quot;d-flex align-items-center justify-content-start margin-top-sm-3&quot;]/div[@class=&quot;chubb-select-container row d-flex align-items-center justify-content-start&quot;]/div[@class=&quot;option-container d-flex justify-content-center&quot;]/div[@class=&quot;option&quot;]</value>
      <webElementGuid>befa9342-51d9-412b-84d9-c1e2008fbb65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@value='12-18']</value>
      <webElementGuid>2b01f34a-b6e3-4b68-b79d-5770632471c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHEVROLET'])[1]/following::div[2]</value>
      <webElementGuid>41bed308-d73e-4ad3-af63-8acbafa820d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué marca es?'])[1]/following::div[7]</value>
      <webElementGuid>cd8dfa2f-01ff-448d-b22a-2ea8c3db9410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GMC'])[1]/preceding::div[1]</value>
      <webElementGuid>6a20cbf2-d851-48bd-b1a3-274ff76c1d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HONDA'])[1]/preceding::div[3]</value>
      <webElementGuid>1f9258a9-d9f7-44f6-925b-13fc9ca03169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FORD']/parent::*</value>
      <webElementGuid>46e0d03f-d97e-4603-bcef-adb2e8411f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//chubb-select/div/div/div[2]/div</value>
      <webElementGuid>271d4808-83ff-429a-bcca-46a0965efdbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' FORD ' or . = ' FORD ')]</value>
      <webElementGuid>21cc7957-f605-44c9-8679-9e7eb396b77a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
