<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MUSTANG</name>
   <tag></tag>
   <elementGuidId>e2ab3349-d298-4f19-9b38-90e7a1ff6f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@value='381391068']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2a9bdf0-9005-44fe-8e86-319733313845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6afe64a8-c9f9-4b54-9576-8c760d556dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>381391068</value>
      <webElementGuid>a8050301-0dbd-4ca6-81d8-951e9d89f310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> MUSTANG </value>
      <webElementGuid>134a41b2-a243-47b2-b08b-f6570af3a8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/block-ui[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row page-container IE-footer-container&quot;]/div[@class=&quot;col-12 p-0 content-wrap&quot;]/app-quote[1]/div[@class=&quot;d-flex flex-column&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/app-model[1]/div[@class=&quot;col-sm-12 offset-sm-0 col-md-10 offset-md-1 col-lg-8 offset-lg-2&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-12 col-lg-8 col-xl-8 col-xxl-7&quot;]/chubb-select[1]/div[@class=&quot;d-flex align-items-center justify-content-start margin-top-sm-3&quot;]/div[@class=&quot;chubb-select-container row d-flex align-items-center justify-content-start&quot;]/div[@class=&quot;option-container d-flex justify-content-center&quot;]/div[@class=&quot;option&quot;]</value>
      <webElementGuid>2233c122-6a47-46c4-9e15-5b6f787db2e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@value='381391068']</value>
      <webElementGuid>87dee5a6-c6ae-49d3-911d-5b71201d8288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FUSION'])[1]/following::div[2]</value>
      <webElementGuid>0f09e793-0775-480b-b308-3f1f6cd044ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FIESTA'])[1]/following::div[4]</value>
      <webElementGuid>d959c7f8-aaf6-434c-9b2c-4f3ede090545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PICK UP FORD'])[1]/preceding::div[1]</value>
      <webElementGuid>b4ff4772-68c1-4872-acfd-5fb48c857d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PICK UP LOBO'])[1]/preceding::div[3]</value>
      <webElementGuid>7e7efa03-2c51-41b6-a033-32dfbc2efa78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MUSTANG']/parent::*</value>
      <webElementGuid>97c916dc-c106-4b9b-99b1-78219de0e811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div</value>
      <webElementGuid>f3c86949-ce96-4846-9e92-1c88385a1c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' MUSTANG ' or . = ' MUSTANG ')]</value>
      <webElementGuid>fb184e4c-c297-47a0-a3f6-37f84d2ba60e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
