<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Acepto   el   Aviso de Privacidad   y_407862</name>
   <tag></tag>
   <elementGuidId>a7465228-3cca-429b-99e0-107d19aeba2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.mat-checkbox-layout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='legal-checkbox']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>18c5ca4e-fde7-4947-98bd-15eee9d1b3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-layout</value>
      <webElementGuid>deba6ab8-c1bd-49d0-ac16-f9279b2bfae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>legal-checkbox-input</value>
      <webElementGuid>4f228651-80c1-4a41-bfb9-8122a1bc9200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Acepto   el   Aviso de Privacidad   y los   Términos, Exclusiones y Condiciones Generales  y que me contacten por teléfono como fin de soporte o seguimiento al proceso.</value>
      <webElementGuid>618e80d7-be89-4441-9ba8-96a93b2212ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;legal-checkbox&quot;)/label[@class=&quot;mat-checkbox-layout&quot;]</value>
      <webElementGuid>a90c4763-c959-4a79-a3a7-9bdf6f1def2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='legal-checkbox']/label</value>
      <webElementGuid>fb87f40e-97f4-43c0-b026-a12f1fa79c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correo electrónico'])[1]/following::label[1]</value>
      <webElementGuid>87fd18b0-1436-4944-a964-0567b04ceeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teléfono'])[1]/following::label[2]</value>
      <webElementGuid>39f6563b-af20-4051-8c99-c39687e1ddb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox/label</value>
      <webElementGuid>a2c035e8-5e43-4f94-99e5-62e9ac4c852b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '     Acepto   el   Aviso de Privacidad   y los   Términos, Exclusiones y Condiciones Generales  y que me contacten por teléfono como fin de soporte o seguimiento al proceso.' or . = '     Acepto   el   Aviso de Privacidad   y los   Términos, Exclusiones y Condiciones Generales  y que me contacten por teléfono como fin de soporte o seguimiento al proceso.')]</value>
      <webElementGuid>6d37cd3e-8573-4060-8375-dfedacdc738d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
