<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mostrar</name>
   <tag></tag>
   <elementGuidId>a0b13fb5-0300-4061-a585-3cae0204de27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maskRfc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='maskRfc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a13fe7b-8eaf-401c-990c-5be783fa6cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>c213c42c-91b7-42e2-820d-c6c4b45a8d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-suffix w-auto citi-h6</value>
      <webElementGuid>2ce5bf34-085e-4492-8ebc-5737f5c808f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maskRfc</value>
      <webElementGuid>819e7ab3-6577-4281-b59b-c44786b57ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mostrar</value>
      <webElementGuid>5901cc56-0630-4383-8051-48b285d05b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maskRfc&quot;)</value>
      <webElementGuid>41190096-30ac-428b-bf77-a12615f785d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='maskRfc']</value>
      <webElementGuid>cdbad260-f61f-44f4-a890-57899f764840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div[3]/div/div/div/a</value>
      <webElementGuid>85b5013a-5372-467d-becb-64b85e0c1c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mostrar')]</value>
      <webElementGuid>9b64022f-36ef-48a2-9ef5-fd8f4c53a072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFC'])[1]/following::a[1]</value>
      <webElementGuid>c4827691-618e-46ee-ad75-ca87d0bcab78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crearemos el RFC con tus datos'])[1]/preceding::a[1]</value>
      <webElementGuid>ced527ed-9c0a-4e35-a400-4fb58619329a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mostrar']/parent::*</value>
      <webElementGuid>4204fb5d-df11-47ba-81a7-6984027a7764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>7e3695c9-bae3-4908-b166-a7d20775e255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a</value>
      <webElementGuid>0be25928-ee72-4484-92f7-d2e0aa617d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'maskRfc' and (text() = 'Mostrar' or . = 'Mostrar')]</value>
      <webElementGuid>dc604479-fd11-47ac-9074-cc603983b1e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
