<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ocultar</name>
   <tag></tag>
   <elementGuidId>560efaa8-8fcb-406e-88a7-e0a30d91151b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maskRfc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='maskRfc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f02dc74-d54a-4863-9615-1d974742f9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>c791f955-8cdf-47dd-abe9-a00076371c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-suffix w-auto citi-h6</value>
      <webElementGuid>67fe7f89-545b-4ec6-9a5f-7b542b64e4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maskRfc</value>
      <webElementGuid>d96325c1-79c2-40af-b5c2-9ba323e18090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ocultar</value>
      <webElementGuid>e247c909-aa04-4b77-b072-ff8f9b0eeaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maskRfc&quot;)</value>
      <webElementGuid>4cdefd2d-ef2e-4cd2-9cfa-0e7d48ac6a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='maskRfc']</value>
      <webElementGuid>9d269f50-8d03-40a0-8b2c-f74ff097b32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div[3]/div/div/div/a</value>
      <webElementGuid>a9788100-254f-4ad9-8a28-9f3746d20ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ocultar')])[2]</value>
      <webElementGuid>6b981464-fc98-4b16-aae0-1ff5c43cc920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFC'])[1]/following::a[1]</value>
      <webElementGuid>57a52efc-6749-4de8-a1ba-2aca7bc0e700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crearemos el RFC con tus datos'])[1]/preceding::a[1]</value>
      <webElementGuid>d5df9c8f-b6cc-42be-ac20-fcf5b1e93d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>d7683e1b-349c-41b3-b053-d6a96bec4460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a</value>
      <webElementGuid>00a4c461-0ada-4186-bb10-1d402c0ef5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'maskRfc' and (text() = 'Ocultar' or . = 'Ocultar')]</value>
      <webElementGuid>49256a38-7954-4d2b-a045-5ae2ef2a11ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
