<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_S</name>
   <tag></tag>
   <elementGuidId>491b2186-1070-40af-a674-1d37910ac7be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paso01Event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='paso01Event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>483ecda9-a7a6-461f-90a4-a7855166f909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paso01Event</value>
      <webElementGuid>59aa578c-76bb-4dad-920a-28760ba18588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option</name>
      <type>Main</type>
      <value>CREDITO</value>
      <webElementGuid>b8815fa3-dc3c-4520-94cb-c2b6d7322383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-button variant-white size-sm mr-20</value>
      <webElementGuid>b3262d14-8c85-41b0-a8e3-c81a78e9131f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>metrica.button('TienesTDC|Si')</value>
      <webElementGuid>e86914c1-f9e9-4c59-b297-c4efadfc1202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sí</value>
      <webElementGuid>7f62c252-5147-4526-974d-00fa35e25f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paso01Event&quot;)</value>
      <webElementGuid>e379741a-704a-4ee8-962b-e1dedde1d80a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='paso01Event']</value>
      <webElementGuid>be843aca-0fb4-484d-a80a-a48ec9b69015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='step0']/div/div[2]/button</value>
      <webElementGuid>9fd5fdba-1728-4cf0-b8b1-2c3b58a1143e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tarjeta de crédito activa'])[1]/following::button[1]</value>
      <webElementGuid>1403ffd0-b07f-4b37-933b-98c22fca94f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[2]/following::button[1]</value>
      <webElementGuid>92e49217-7d34-4448-8625-40efbc4a285e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>d58deeb5-bcf3-47be-9e90-d363df165ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí'])[2]/preceding::button[2]</value>
      <webElementGuid>047ab1cb-fe11-4a7e-bbae-674a6d2a4d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sí']/parent::*</value>
      <webElementGuid>fc79f9a8-bb9a-4da5-b2d9-a312437a99a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/section/div/div[2]/button</value>
      <webElementGuid>006b7ebe-9e7e-4264-b750-79a40a1429a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'paso01Event' and (text() = 'Sí' or . = 'Sí')]</value>
      <webElementGuid>2421a8d8-bf8b-4dc4-840a-966d00aa8d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
