<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuar</name>
   <tag></tag>
   <elementGuidId>de4547a4-2136-4661-910b-39b2bd53377d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continuar1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='continuar1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39159c53-3921-4168-a45d-8ef35691dac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5009282-638d-48e5-93c4-ba310ff6477b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continuar1</value>
      <webElementGuid>d482153a-c3b6-4a84-85e6-44094719564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stepValida citi-button variant-primary size-sm</value>
      <webElementGuid>de84526f-8cd3-4b32-9a0a-11e5701b3aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Continuar
            </value>
      <webElementGuid>3f232233-187f-4252-8a99-d3b5a37a7f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continuar1&quot;)</value>
      <webElementGuid>85e7ca6c-3953-4b5c-91d7-8aa55d8e6134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='continuar1']</value>
      <webElementGuid>e56f9db7-1c44-40a3-848e-9e5f9d7fcd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div[5]/div/button</value>
      <webElementGuid>c8bb4692-6065-4e9e-9f92-43e6cfc5629d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡Tranquilo! No lo utilizaremos para llamarte.'])[1]/following::button[1]</value>
      <webElementGuid>734618ba-2c49-4056-a75e-f4ec3079f078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Celular'])[1]/following::button[1]</value>
      <webElementGuid>2b2d00a6-5089-40f8-b675-925b9bd4db8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>1dd6e53a-6b61-49fd-a4d8-16a2de905cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'continuar1' and (text() = '
              Continuar
            ' or . = '
              Continuar
            ')]</value>
      <webElementGuid>efbb9a8a-8da1-43cf-8924-276481d1fdd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
