<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dia</name>
   <tag></tag>
   <elementGuidId>ad41f6cb-d20d-4c56-b478-a654b3998b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>css=#fecha-de-nacimiento-control-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id=fecha-de-nacimiento-control-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
