<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre(s)_informacion-personal-control-1</name>
   <tag></tag>
   <elementGuidId>3ae1cdce-9114-4832-b126-985a339f7fa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#informacion-personal-control-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='informacion-personal-control-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbb9b0da-ea6c-48ed-adc0-65f5a4c8d6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>informacion-personal-control-1</value>
      <webElementGuid>4954c9b1-a90d-4c25-9ef1-1ee644108f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>informacion-personal-description-1</value>
      <webElementGuid>41d695a9-3059-493e-a0fa-bacac3902295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-input firstMayuscula</value>
      <webElementGuid>5bccb205-951d-4102-ab61-1c49fd37a0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83c01c75-7ea0-4ed2-b9f5-ffb531ca5820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Luis Enrique</value>
      <webElementGuid>8639c7d4-2647-4bfa-85ca-d4ef941e71aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$</value>
      <webElementGuid>ea19e4e3-433d-4ecf-891f-58682d11b88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>085e55a6-3595-43b2-ab7a-a9ed3263a54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tipo</name>
      <type>Main</type>
      <value>field_Name</value>
      <webElementGuid>1e7368c6-f31e-4d4e-8d6e-86c3520862c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;informacion-personal-control-1&quot;)</value>
      <webElementGuid>3acc270c-3467-434b-b9c3-c724773527ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='informacion-personal-control-1']</value>
      <webElementGuid>b4184861-f336-42cc-95ce-a357a59d6693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div/div/div/div/div/input</value>
      <webElementGuid>847a40e7-f169-4c57-b954-7c2e074c595d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>2c85d0aa-2e1e-4b4f-a042-d579fbdc5995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'informacion-personal-control-1' and @type = 'text' and @placeholder = 'Luis Enrique']</value>
      <webElementGuid>10ea0f18-e877-4f58-b38a-dc14a420bf8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
