<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Correo electrnico_correo-electronico-_f6d4ce</name>
   <tag></tag>
   <elementGuidId>687ef66b-aee9-4f30-92ed-d54f92d3b2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#correo-electronico-control-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='correo-electronico-control-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdda9cc1-291c-414c-9278-2371fa337bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>correo-electronico-control-1</value>
      <webElementGuid>5e6711ad-dbf3-43ef-9533-fd421a6b555d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-input </value>
      <webElementGuid>3919773a-20e5-4908-98c6-a4c0fb44ed96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2b354c18-4f41-4daa-b245-74d3df07dff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ejemplo@gmail.com</value>
      <webElementGuid>ddccdec6-c646-4173-9c19-09c2fc0ce955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>09b60fd1-336f-444c-9443-79b57e8e6a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9ñÑ\-_.@]+$</value>
      <webElementGuid>75afc541-24e6-48d2-8ede-951f00b50727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>79082347-928f-4d72-bf86-738632e1c5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tipo</name>
      <type>Main</type>
      <value>field_Email</value>
      <webElementGuid>c7b66e69-7695-4b04-8b3e-ba5918a0ae03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;correo-electronico-control-1&quot;)</value>
      <webElementGuid>64cfbf56-794c-401c-8139-d55535912ece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='correo-electronico-control-1']</value>
      <webElementGuid>da9d9e21-200f-4d3e-9604-696ac5573f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div[4]/div/div/div/input</value>
      <webElementGuid>4419358f-a8ca-4592-aaa4-87b12180d29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>641d25b7-552a-4511-b324-b40ce093c807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'correo-electronico-control-1' and @type = 'email' and @placeholder = 'ejemplo@gmail.com']</value>
      <webElementGuid>9afaefe2-bf5e-4f15-8b06-43bd8c220f65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
