<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primer Apellido_informacion-personal-_dab627</name>
   <tag></tag>
   <elementGuidId>fd7dd57c-4793-4bb6-a196-d64ba11880f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#informacion-personal-control-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='informacion-personal-control-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>995b307e-5c30-41cb-8643-75426a1484b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>informacion-personal-control-2</value>
      <webElementGuid>0ed99c68-3a0d-4ff8-a5a0-af72126bca6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09bd8fb7-e2a1-43bf-a4fe-481c402c4310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-input firstMayuscula</value>
      <webElementGuid>3cf0a291-3e49-477d-a6d5-365cba6c1322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$</value>
      <webElementGuid>1a0e93eb-a90c-4068-af58-11e1fb3d52d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>da9a222d-6f83-4933-9df4-48ddb145e105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tipo</name>
      <type>Main</type>
      <value>field_SecondName</value>
      <webElementGuid>7a920504-2ee8-4833-a952-c8e36234c4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;informacion-personal-control-2&quot;)</value>
      <webElementGuid>a7760c14-f912-4892-9b58-5e05910aa1af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='informacion-personal-control-2']</value>
      <webElementGuid>a6109639-729b-45ae-993b-58364eb2df8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div/div[2]/div/div/div/input</value>
      <webElementGuid>188da523-dff9-48ef-81b0-7c3814ff5b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>de9e9964-d165-4dfa-bbe1-041da37d024b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'informacion-personal-control-2' and @type = 'text']</value>
      <webElementGuid>ad04ddec-300e-4a6b-862b-4e6a57286f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
