<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Celular_celular-control-1</name>
   <tag></tag>
   <elementGuidId>052c026d-79d3-4f61-87d7-69a50d9861b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#celular-control-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='celular-control-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f6afb5a-d48e-4cff-8c9a-e27211dd6561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>celular-control-1</value>
      <webElementGuid>ece85df0-6160-4baa-95fb-e0ba0f40bc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-input</value>
      <webElementGuid>6dad9813-dcfc-4347-8c58-22f2d685dfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ada2e80-705d-4c92-9377-0fb54e3fba11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>00 00 00 00 00</value>
      <webElementGuid>9e2fae34-82d7-4656-b38a-66041da79401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9 ]+$</value>
      <webElementGuid>0a52e790-39c4-48e6-8d9d-85d42c729782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>58be261f-5e4a-43b5-a72d-ee69c5a28a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tipo</name>
      <type>Main</type>
      <value>field_cellPhone</value>
      <webElementGuid>d3f37030-8927-4243-bbd8-5fa4f2dd4fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;celular-control-1&quot;)</value>
      <webElementGuid>18d87edc-8f95-41ae-b7fd-0dbb9b50aede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='celular-control-1']</value>
      <webElementGuid>9ac80cb1-d869-4713-837f-40d0953aa737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div[4]/div[2]/div/div/input</value>
      <webElementGuid>79f95761-6119-4a37-86a9-77ff42be7961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>a0d182f0-fc76-4b32-ba2a-2ca5327ce16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'celular-control-1' and @type = 'text' and @placeholder = '00 00 00 00 00']</value>
      <webElementGuid>1247750b-dbaa-4fba-a97f-992d30664a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
