<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Segundo Apellido_informacion-personal_ab76c1</name>
   <tag></tag>
   <elementGuidId>b1d176c3-6975-453d-ba58-6f5f079b5c60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#informacion-personal-control-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='informacion-personal-control-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9354ee3-7e35-4e9b-a2ee-46e079bd848e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>informacion-personal-control-3</value>
      <webElementGuid>39bcd111-c1b8-48cb-abaf-9ee07e27d7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2838b687-b11e-4f22-bd62-b34dc815e9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-input firstMayuscula</value>
      <webElementGuid>20216aed-7ef9-47ae-b821-0ec069bfa354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$</value>
      <webElementGuid>629013f1-a22a-4e6f-877d-a05b52bc0417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>2e731a91-0274-4385-8fd0-04ad1a634419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tipo</name>
      <type>Main</type>
      <value>field_MothersSurname</value>
      <webElementGuid>91485b7c-d45e-4365-bcda-4c465a1f818d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;informacion-personal-control-3&quot;)</value>
      <webElementGuid>db5aeda7-e457-4cc7-b945-64fc2fc22372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='informacion-personal-control-3']</value>
      <webElementGuid>dd097772-4a7d-4d8b-8927-ceb7df5658d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>32afa08e-5330-41d6-b880-39321511031a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>8d31bc80-d792-4116-ac5a-29ff1841439a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'informacion-personal-control-3' and @type = 'text']</value>
      <webElementGuid>0e3b71e4-66de-4049-8a11-53ca7f1300eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
