<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_S</name>
   <tag></tag>
   <elementGuidId>0ad8e19e-df45-4db6-b856-01e76d2ec943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paso01Event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='paso01Event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>617eb6e7-55b1-41cb-935f-d8979651f5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paso01Event</value>
      <webElementGuid>9e512018-dc49-4252-abf7-070209f29a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option</name>
      <type>Main</type>
      <value>CREDITO</value>
      <webElementGuid>a4f56d5b-f262-4415-9a9d-92edb6c731f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-button variant-white size-sm mr-20</value>
      <webElementGuid>970ed3aa-4880-4032-805c-7f70431e1e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>metrica.button('TienesTDC|Si')</value>
      <webElementGuid>41251fbf-6250-4393-9b08-1008867d0525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sí</value>
      <webElementGuid>fb438b9d-80ae-4ed4-8ce9-70126e64a700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paso01Event&quot;)</value>
      <webElementGuid>782fd795-57b7-4c7c-9ae6-ee5eb1af3ec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='paso01Event']</value>
      <webElementGuid>0ae4558d-af27-4fbe-b3ef-9c4f2a62a8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='step0']/div/div[2]/button</value>
      <webElementGuid>b6e1d0af-bc83-4996-b7ea-60e459927616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tarjeta de crédito activa'])[1]/following::button[1]</value>
      <webElementGuid>f396d69f-d3d9-4128-bb5e-1b1a3843790d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[2]/following::button[1]</value>
      <webElementGuid>57052da2-d90a-44b0-9eb8-9fc6b670b19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>12729d0c-fa52-4cbb-bfb3-c2364c84ac1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí'])[2]/preceding::button[2]</value>
      <webElementGuid>b3994f25-9bd0-438c-9b61-cd57702ccdc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sí']/parent::*</value>
      <webElementGuid>e52d2917-cecb-4ee0-bbd9-8caa2117f09a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/section/div/div[2]/button</value>
      <webElementGuid>dc8fa289-d1d2-4fc6-9eaf-405d9d7caaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'paso01Event' and (text() = 'Sí' or . = 'Sí')]</value>
      <webElementGuid>737b9a36-1bcf-4c15-821c-77a0b2a2a531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
