<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primer Apellido_informacion-personal-_dab627</name>
   <tag></tag>
   <elementGuidId>b210c538-58be-41c0-a087-02ca70eed83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#informacion-personal-control-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='informacion-personal-control-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2fb09f9-62b4-43ad-9a42-752f14ec5b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>informacion-personal-control-2</value>
      <webElementGuid>3b1c477d-f85f-4746-8450-f3c0d7e39980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3d98409-d999-43c3-acba-81d3e1c707b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-input firstMayuscula</value>
      <webElementGuid>55a1c305-9214-4e15-b695-d155139886be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$</value>
      <webElementGuid>87fce208-83cd-4d29-aecc-7507a43d6f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>887029e6-e550-4221-8254-69269c38ca8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tipo</name>
      <type>Main</type>
      <value>field_SecondName</value>
      <webElementGuid>8e8d182f-3838-4c31-a2e6-6a70ae202cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;informacion-personal-control-2&quot;)</value>
      <webElementGuid>636f3f6b-9ff0-45dc-aad1-3b49c6378464</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='informacion-personal-control-2']</value>
      <webElementGuid>873bb2b7-4fcf-4ef6-9691-1ba5f7f7c604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div/div[2]/div/div/div/input</value>
      <webElementGuid>76fb816f-4f99-45eb-827e-440fea3d18c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>7bbe0ad1-b4ec-45a1-ad2c-79c9e2109a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'informacion-personal-control-2' and @type = 'text']</value>
      <webElementGuid>c42c74de-406d-41ba-96b0-e4e720451dce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
