<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre(s)_informacion-personal-control-1</name>
   <tag></tag>
   <elementGuidId>7bcd50b6-d8e5-4783-a8dd-dc9e4fd7fc61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#informacion-personal-control-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='informacion-personal-control-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82f17204-ebea-4d1d-8147-577f7a76bdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>informacion-personal-control-1</value>
      <webElementGuid>caa7cd6a-3658-4433-976f-49c2ebe3c43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>informacion-personal-description-1</value>
      <webElementGuid>cd835ca3-7303-4acf-a64d-721a707af91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>citi-textfield-input firstMayuscula</value>
      <webElementGuid>88fa5425-509d-4999-bf13-f2bc6f12baa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdfd0e7f-3628-4b5d-9fad-8f832231f0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Luis Enrique</value>
      <webElementGuid>e5fdc80a-b80e-4eac-b488-26e9faaf2496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$</value>
      <webElementGuid>5de281e9-d686-452c-809b-939a4982cd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3d14f5a5-7d3d-4adc-a21c-2628470680c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tipo</name>
      <type>Main</type>
      <value>field_Name</value>
      <webElementGuid>c653cebd-cca4-4705-a80b-a4936f82cfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;informacion-personal-control-1&quot;)</value>
      <webElementGuid>4e640f60-b6b3-4d13-93d4-672fd3b02392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='informacion-personal-control-1']</value>
      <webElementGuid>b7a864fd-c673-4902-a7f0-89fe8546baa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='step1']/div/div/div/div/div/input</value>
      <webElementGuid>a0b1da2a-933e-42ff-ad6b-62b23d267b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>d9b4eef8-0ea8-4454-812d-7a0e4770f8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'informacion-personal-control-1' and @type = 'text' and @placeholder = 'Luis Enrique']</value>
      <webElementGuid>e35c5754-9220-4ebc-a186-1720f8d07e39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
